is_diagonal(m) := block([col_size, row_size],
  col_size : length(m),
  row_size : length(m[1]),
  is(col_size = row_size) and is( m = m * diagmatrix(col_size, 1))
  );

get_diag_element(m) := block([len, i],
  len : length(m),
  maplist(lambda([i], m[i,i]), makelist(i, i, len))
  );

is_same_diag(a, x) := block([],
  is_diagonal(a) and is_diagonal(x) and does_hold( sort(get_diag_element(a)) = sort(get_diag_element(x)) )
  );