load("myassert.mac");
load("../is_orthonormal_basis.mac");

test_assert( is_orthonormal_basis([[1,0], [0,1]]) );
test_assert( is_orthonormal_basis([[1/sqrt(2), 1/sqrt(2)], [1/sqrt(2), -1/sqrt(2)]]) );
test_assert( not is_orthonormal_basis([[1/sqrt(2), 1/sqrt(2)], [1/sqrt(2), -1]]) );
test_assert( is_orthonormal_basis([[1,0,0], [0,1,0]]) );
test_assert( is_orthonormal_basis([[1,%i,0]/sqrt(2), [1,-%i,0]/sqrt(2)]) );
test_assert( is_orthonormal_basis([[1/sqrt(2),%i/sqrt(2),0],[1/sqrt(6),-(%i/sqrt(6)),2/sqrt(6)]]) );
test_assert( is_orthonormal_basis([[%i/sqrt(2),0,1/sqrt(2)],[(1-%i)/(2*sqrt(2)),1/sqrt(2),(1+%i)/(2*sqrt(2))]]) );
test_assert( is_orthonormal_basis([[%i/sqrt(2),0,1/sqrt(2)],[(1/2-%i/2)/sqrt(2),1/sqrt(2),(1/2+%i/2)/sqrt(2)]]) );
