load("myassert.mac");
load("../is_same_echelon.mac");

test_assert( is_same_echelon(matrix([1,2], [1,1]), matrix([1,2], [0, 1])) );

a : matrix([1,2,3,5,1],[4,5,6,5,1],[7,8,9,1,1],[7,8,9,2,2]) $
m : echelon(a)$
test_assert( is_same_echelon(a, m) ) ;
m : matrix([1,2,3,5,1],[1,5,6,5,1],[1,8,9,1,1],[7,8,9,2,2]) $
test_assert( not is_same_echelon(a, m) ) ;

m : matrix([1,2], [0,1]) $
test_assert( is_echelon(m) ) ;
m : matrix([1,2], [1,1]) $
test_assert( not is_echelon(m) ) ;
m : matrix([0,2], [1,1]) $
test_assert( not is_echelon(m) ) ;
m : matrix([0,0], [0,0]) $
test_assert( is_echelon(m) ) ;
m : matrix([1, 0, 1], [0, 1, 0], [0, 0, 0]) $
test_assert( is_echelon(m) ) ;
m : matrix([1, 0, 1], [0, 1, 0], [0, 1, 0]) $
test_assert( not is_echelon(m) ) ;