load("myassert.mac");
load("../does_hold.mac");

test_assert( does_hold( 2/sqrt(2) = sqrt(2) ) );
test_assert( does_hold( sqrt(2/3) = 2/sqrt(6) ) );
test_assert( does_hold( -sqrt(2/3) = -2/sqrt(6) ) );
test_assert( does_hold( abs(x) = sqrt(x^2)  ) );
test_assert( does_hold( log(2*y^2*x^2) = 2 * log(x) + 2*log(y) + log(2) ) );
test_assert( does_hold( sinh(2) = (%e^4-1)/(2*%e^2) ) );
test_assert( does_hold( %e^(%i*%pi) = -1 ) );
test_assert( does_hold( matrix([1,2],[3,4]) = matrix([1,2],[3,4]) ) );
test_assert( does_hold( %e^1-%e^(-1) = 2*sinh(1) ) );
test_assert( does_hold( x^(1/2) = sqrt(x) ) );

test_assert( does_hold( 2*%pi*(sin((2)^(1/2))-2^(1/2)*cos((2)^(1/2))) = -2*%pi*(sqrt(2)*cos(sqrt(2))-sin(sqrt(2))) ) );